"""Contract test: the plugin-bundled .mcp.json manifest.

Unlike ~/.claude.json (generated by cli/_init_helpers.py), this file is
statically hand-maintained — it can't be templated at plugin-install time.
Nothing else loads or validates it, so a drift between this literal and
RunSkillConfig's default would go unnoticed.
"""

from __future__ import annotations

import json

import pytest

from autoskillit.config import RunSkillConfig
from autoskillit.core.paths import pkg_root

pytestmark = [pytest.mark.layer("cli"), pytest.mark.small]


def test_bundled_mcp_json_timeout_matches_default_mcp_tool_timeout_sec():
    manifest_path = pkg_root() / ".mcp.json"
    data = json.loads(manifest_path.read_text())

    assert data["mcpServers"]["autoskillit"]["timeout"] == int(
        RunSkillConfig().mcp_tool_timeout_sec * 1000
    )


def test_bundled_autoskillit_server_is_a_per_client_stdio_child():
    manifest_path = pkg_root() / ".mcp.json"
    data = json.loads(manifest_path.read_text())
    entry = data["mcpServers"]["autoskillit"]

    assert entry["command"] == "autoskillit"
    assert "url" not in entry
    assert entry.get("type", "stdio") == "stdio"
