"""IL-2 recipe helper primitives — git, I/O, rule/skill helpers, registry utils (#4671 Phase D).

Sub-package of :mod:`autoskillit.recipe`. Real implementations live in this
sub-package; backward-compat shims at the old ``recipe/_<helper>.py`` paths
preserve existing import sites.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._git_helpers import (
        _GIT_REMOTE_COMMAND_RE,
        _LITERAL_ORIGIN_RE,
        annotations,
        cmd_keyword_pattern,
    )  # noqa: F401
    from ._io_loading import (
        _SCRIPTS_PLACEHOLDER,
        _TEMP_PLACEHOLDER,
        INPUT_REF_RE,
        NON_RECIPE_DIRS,
        RECIPE_SCAN_DIRS,
        S_ISDIR,
        Any,
        Iterable,
        LoadReport,
        LoadResult,
        Path,
        Protocol,
        PurePosixPath,
        Recipe,
        RecipeInfo,
        RecipeSource,
        _cached_recipe_candidates,
        _cached_recipe_collection,
        _CachedRecipeCollection,
        _CandidateCollector,
        _CandidateEnumerator,
        _collect_recipes_from_candidates,
        _collect_relative_recipe_candidates,
        _DirectorySignature,
        _discover_recipe_collection,
        _enumerate_candidates_in_scan_dirs,
        _parse_recipe_candidate,
        _recipe_directory_signature,
        _recipe_input_signature,
        _RecipeInputSignature,
        _RecipeParser,
        _substitute_recipe_values,
        assert_no_raw_placeholders,
        clear_recipe_discovery_caches,
        fast_loads,
        get_logger,
        is_recipe_scan_path,
        load_recipe_dict,
        load_recipe_dict_with_declarations,
        load_yaml,
        logger,
        lru_cache,
        pkg_root,
        substitute_scripts_placeholder,
        substitute_temp_placeholder,
    )  # noqa: F401
    from ._registry_utils import (
        _MISSING_MTIME,
        EXPECTED_SCHEMA_VERSION,
        Final,
        dir_mtime,
        parse_int_field,
    )  # noqa: F401
    from ._rule_helpers import (
        _ARG_TOKEN_PATTERN,
        _MAX_HOPS,
        _PATH_SAFE_LOOKAHEAD,
        _PATH_SAFE_LOOKBEHIND,
        _SENTINEL_TRIGGER_RE,
        _SKILL_CMD_PATTERN,
        TYPE_CHECKING,
        Mapping,
        ValidationContext,
        _build_graph_without_nodes,
        _extract_sentinel_fields,
        _find_cycle_members,
        _identify_optional_output_fields,
        _is_failure_sentinel_value,
        _is_loop_guard_step,
        _load_dispatch_target,
        count_skill_args,
        deque,
        extract_sentinel_json_blocks,
        filter_pruning_false_positives,
        is_failure_stop,
        is_success_stop,
        push_reachable,
    )  # noqa: F401
    from ._skill_helpers import (
        _SKILL_CATEGORY_CACHE,
        _SKILL_NAMES_CACHE,
        _SKILL_TOKEN_RE,
        MULTIPART_SKILL_NAMES,
        SKILL_SEARCH_DIRS,
        SkillLister,
        _get_bundled_skill_names,
        _get_skill_category_map,
        _has_dynamic_skill_name,
        _resolve_skill_md,
        bound_skill_name,
        get_allowed_values_for_skill,
    )  # noqa: F401
    from ._skill_placeholder_parser import (
        _BANNED_CONTENT_SUFFIX_RE,
        _CONTENT_VAR_SIGNAL_RE,
        _DYNAMIC_WRITE_VAR_RE,
        _PROSE_GRAPHQL_EXECUTION_RE,
        _STEP_RE,
        _VRULE_RE,
        _WRITE_SCOPE_RE,
        extract_bash_blocks,
        extract_bash_placeholders,
        extract_blockquote_placeholders,
        extract_blockquote_sections,
        extract_declared_ingredients,
        extract_fenced_blocks,
        extract_git_commands,
        extract_graphql_blocks,
        extract_never_block,
        extract_python_blocks,
        extract_sections,
        extract_step_sections,
        extract_validation_rule_block,
        extract_write_path_declarations,
        has_dynamic_write_path,
        has_prose_graphql_execution,
        shell_vars_assigned,
    )  # noqa: F401


def __getattr__(name: str):
    """Lazily resolve symbols and submodules to avoid eager subpackage loads."""
    if name in _LAZY_MODULES:
        from importlib import import_module

        full = f"{__name__}.{name}"
        mod = import_module(full)
        globals()[name] = mod
        return mod
    mod_name = _LAZY_SYMBOL_TO_MODULE.get(name)
    if mod_name is not None:
        from importlib import import_module

        mod = import_module(f"{__name__}.{mod_name}")
        value = getattr(mod, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


_LAZY_MODULES: frozenset[str] = frozenset(
    {
        "_git_helpers",
        "_io_loading",
        "_rule_helpers",
        "_skill_helpers",
        "_skill_placeholder_parser",
        "_registry_utils",
    }
)

_LAZY_SYMBOL_TO_MODULE: dict[str, str] = {
    "_GIT_REMOTE_COMMAND_RE": "_git_helpers",
    "_LITERAL_ORIGIN_RE": "_git_helpers",
    "annotations": "_registry_utils",
    "cmd_keyword_pattern": "_rule_helpers",
    "Any": "_rule_helpers",
    "INPUT_REF_RE": "_io_loading",
    "Iterable": "_io_loading",
    "LoadReport": "_io_loading",
    "LoadResult": "_io_loading",
    "NON_RECIPE_DIRS": "_io_loading",
    "Path": "_registry_utils",
    "Protocol": "_io_loading",
    "PurePosixPath": "_io_loading",
    "RECIPE_SCAN_DIRS": "_io_loading",
    "Recipe": "_io_loading",
    "RecipeInfo": "_io_loading",
    "RecipeSource": "_io_loading",
    "S_ISDIR": "_io_loading",
    "_CachedRecipeCollection": "_io_loading",
    "_CandidateCollector": "_io_loading",
    "_CandidateEnumerator": "_io_loading",
    "_DirectorySignature": "_io_loading",
    "_RecipeInputSignature": "_io_loading",
    "_RecipeParser": "_io_loading",
    "_SCRIPTS_PLACEHOLDER": "_io_loading",
    "_TEMP_PLACEHOLDER": "_io_loading",
    "_cached_recipe_candidates": "_io_loading",
    "_cached_recipe_collection": "_io_loading",
    "_collect_recipes_from_candidates": "_io_loading",
    "_collect_relative_recipe_candidates": "_io_loading",
    "_discover_recipe_collection": "_io_loading",
    "_enumerate_candidates_in_scan_dirs": "_io_loading",
    "_parse_recipe_candidate": "_io_loading",
    "_recipe_directory_signature": "_io_loading",
    "_recipe_input_signature": "_io_loading",
    "_substitute_recipe_values": "_io_loading",
    "assert_no_raw_placeholders": "_io_loading",
    "clear_recipe_discovery_caches": "_io_loading",
    "fast_loads": "_io_loading",
    "get_logger": "_skill_helpers",
    "is_recipe_scan_path": "_io_loading",
    "load_recipe_dict": "_io_loading",
    "load_recipe_dict_with_declarations": "_io_loading",
    "load_yaml": "_io_loading",
    "logger": "_skill_helpers",
    "lru_cache": "_io_loading",
    "pkg_root": "_skill_helpers",
    "substitute_scripts_placeholder": "_io_loading",
    "substitute_temp_placeholder": "_io_loading",
    "Mapping": "_rule_helpers",
    "TYPE_CHECKING": "_skill_helpers",
    "ValidationContext": "_rule_helpers",
    "_ARG_TOKEN_PATTERN": "_rule_helpers",
    "_MAX_HOPS": "_rule_helpers",
    "_PATH_SAFE_LOOKAHEAD": "_rule_helpers",
    "_PATH_SAFE_LOOKBEHIND": "_rule_helpers",
    "_SENTINEL_TRIGGER_RE": "_rule_helpers",
    "_SKILL_CMD_PATTERN": "_rule_helpers",
    "_build_graph_without_nodes": "_rule_helpers",
    "_extract_sentinel_fields": "_rule_helpers",
    "_find_cycle_members": "_rule_helpers",
    "_identify_optional_output_fields": "_rule_helpers",
    "_is_failure_sentinel_value": "_rule_helpers",
    "_is_loop_guard_step": "_rule_helpers",
    "_load_dispatch_target": "_rule_helpers",
    "count_skill_args": "_rule_helpers",
    "deque": "_rule_helpers",
    "extract_sentinel_json_blocks": "_rule_helpers",
    "filter_pruning_false_positives": "_rule_helpers",
    "is_failure_stop": "_rule_helpers",
    "is_success_stop": "_rule_helpers",
    "push_reachable": "_rule_helpers",
    "MULTIPART_SKILL_NAMES": "_skill_helpers",
    "SKILL_SEARCH_DIRS": "_skill_helpers",
    "SkillLister": "_skill_helpers",
    "_SKILL_CATEGORY_CACHE": "_skill_helpers",
    "_SKILL_NAMES_CACHE": "_skill_helpers",
    "_SKILL_TOKEN_RE": "_skill_helpers",
    "_get_bundled_skill_names": "_skill_helpers",
    "_get_skill_category_map": "_skill_helpers",
    "_has_dynamic_skill_name": "_skill_helpers",
    "_resolve_skill_md": "_skill_helpers",
    "bound_skill_name": "_skill_helpers",
    "get_allowed_values_for_skill": "_skill_helpers",
    "_BANNED_CONTENT_SUFFIX_RE": "_skill_placeholder_parser",
    "_CONTENT_VAR_SIGNAL_RE": "_skill_placeholder_parser",
    "_DYNAMIC_WRITE_VAR_RE": "_skill_placeholder_parser",
    "_PROSE_GRAPHQL_EXECUTION_RE": "_skill_placeholder_parser",
    "_STEP_RE": "_skill_placeholder_parser",
    "_VRULE_RE": "_skill_placeholder_parser",
    "_WRITE_SCOPE_RE": "_skill_placeholder_parser",
    "extract_bash_blocks": "_skill_placeholder_parser",
    "extract_bash_placeholders": "_skill_placeholder_parser",
    "extract_blockquote_placeholders": "_skill_placeholder_parser",
    "extract_blockquote_sections": "_skill_placeholder_parser",
    "extract_declared_ingredients": "_skill_placeholder_parser",
    "extract_fenced_blocks": "_skill_placeholder_parser",
    "extract_git_commands": "_skill_placeholder_parser",
    "extract_graphql_blocks": "_skill_placeholder_parser",
    "extract_never_block": "_skill_placeholder_parser",
    "extract_python_blocks": "_skill_placeholder_parser",
    "extract_sections": "_skill_placeholder_parser",
    "extract_step_sections": "_skill_placeholder_parser",
    "extract_validation_rule_block": "_skill_placeholder_parser",
    "extract_write_path_declarations": "_skill_placeholder_parser",
    "has_dynamic_write_path": "_skill_placeholder_parser",
    "has_prose_graphql_execution": "_skill_placeholder_parser",
    "shell_vars_assigned": "_skill_placeholder_parser",
    "EXPECTED_SCHEMA_VERSION": "_registry_utils",
    "Final": "_registry_utils",
    "_MISSING_MTIME": "_registry_utils",
    "dir_mtime": "_registry_utils",
    "parse_int_field": "_registry_utils",
}

__all__ = [
    "_GIT_REMOTE_COMMAND_RE",
    "_LITERAL_ORIGIN_RE",
    "annotations",
    "cmd_keyword_pattern",
    "Any",
    "INPUT_REF_RE",
    "Iterable",
    "LoadReport",
    "LoadResult",
    "NON_RECIPE_DIRS",
    "Path",
    "Protocol",
    "PurePosixPath",
    "RECIPE_SCAN_DIRS",
    "Recipe",
    "RecipeInfo",
    "RecipeSource",
    "S_ISDIR",
    "_CachedRecipeCollection",
    "_CandidateCollector",
    "_CandidateEnumerator",
    "_DirectorySignature",
    "_RecipeInputSignature",
    "_RecipeParser",
    "_SCRIPTS_PLACEHOLDER",
    "_TEMP_PLACEHOLDER",
    "_cached_recipe_candidates",
    "_cached_recipe_collection",
    "_collect_recipes_from_candidates",
    "_collect_relative_recipe_candidates",
    "_discover_recipe_collection",
    "_enumerate_candidates_in_scan_dirs",
    "_parse_recipe_candidate",
    "_recipe_directory_signature",
    "_recipe_input_signature",
    "_substitute_recipe_values",
    "annotations",
    "assert_no_raw_placeholders",
    "clear_recipe_discovery_caches",
    "fast_loads",
    "get_logger",
    "is_recipe_scan_path",
    "load_recipe_dict",
    "load_recipe_dict_with_declarations",
    "load_yaml",
    "logger",
    "lru_cache",
    "pkg_root",
    "substitute_scripts_placeholder",
    "substitute_temp_placeholder",
    "Any",
    "Mapping",
    "Path",
    "TYPE_CHECKING",
    "ValidationContext",
    "_ARG_TOKEN_PATTERN",
    "_MAX_HOPS",
    "_PATH_SAFE_LOOKAHEAD",
    "_PATH_SAFE_LOOKBEHIND",
    "_SENTINEL_TRIGGER_RE",
    "_SKILL_CMD_PATTERN",
    "_build_graph_without_nodes",
    "_extract_sentinel_fields",
    "_find_cycle_members",
    "_identify_optional_output_fields",
    "_is_failure_sentinel_value",
    "_is_loop_guard_step",
    "_load_dispatch_target",
    "annotations",
    "cmd_keyword_pattern",
    "count_skill_args",
    "deque",
    "extract_sentinel_json_blocks",
    "filter_pruning_false_positives",
    "get_logger",
    "is_failure_stop",
    "is_success_stop",
    "logger",
    "push_reachable",
    "MULTIPART_SKILL_NAMES",
    "Path",
    "SKILL_SEARCH_DIRS",
    "SkillLister",
    "TYPE_CHECKING",
    "_SKILL_CATEGORY_CACHE",
    "_SKILL_NAMES_CACHE",
    "_SKILL_TOKEN_RE",
    "_get_bundled_skill_names",
    "_get_skill_category_map",
    "_has_dynamic_skill_name",
    "_resolve_skill_md",
    "annotations",
    "bound_skill_name",
    "get_allowed_values_for_skill",
    "get_logger",
    "logger",
    "pkg_root",
    "_BANNED_CONTENT_SUFFIX_RE",
    "_CONTENT_VAR_SIGNAL_RE",
    "_DYNAMIC_WRITE_VAR_RE",
    "_PROSE_GRAPHQL_EXECUTION_RE",
    "_STEP_RE",
    "_VRULE_RE",
    "_WRITE_SCOPE_RE",
    "annotations",
    "extract_bash_blocks",
    "extract_bash_placeholders",
    "extract_blockquote_placeholders",
    "extract_blockquote_sections",
    "extract_declared_ingredients",
    "extract_fenced_blocks",
    "extract_git_commands",
    "extract_graphql_blocks",
    "extract_never_block",
    "extract_python_blocks",
    "extract_sections",
    "extract_step_sections",
    "extract_validation_rule_block",
    "extract_write_path_declarations",
    "has_dynamic_write_path",
    "has_prose_graphql_execution",
    "shell_vars_assigned",
    "EXPECTED_SCHEMA_VERSION",
    "Final",
    "Path",
    "_MISSING_MTIME",
    "annotations",
    "dir_mtime",
    "parse_int_field",
]
