"""L0 foundation sub-package: types, logging, and I/O primitives.

Re-exports the full public surface of core.types, core.logging, and core.io
so callers can do either `from autoskillit.core import get_logger` or the
explicit `from autoskillit.core.logging import get_logger`.
"""

from .io import (
    YAMLError,
    _atomic_write,
    dump_yaml_str,
    ensure_project_temp,
    load_yaml,
)
from .logging import (
    configure_logging,
    get_logger,
)
from .paths import (
    GENERATED_FILES,
    claude_code_log_path,
    claude_code_project_dir,
    is_git_worktree,
    pkg_root,
)
from .types import (
    AUTOSKILLIT_INSTALLED_VERSION,
    AUTOSKILLIT_SKILL_PREFIX,
    CONTEXT_EXHAUSTION_MARKER,
    GATED_TOOLS,
    PIPELINE_FORBIDDEN_TOOLS,
    RESERVED_LOG_RECORD_KEYS,
    SKILL_COMMAND_PREFIX,
    SKILL_TOOLS,
    UNGATED_TOOLS,
    AuditStore,
    ChannelConfirmation,
    CleanupResult,
    CloneManager,
    DatabaseReader,
    FailureRecord,
    GatePolicy,
    GitHubFetcher,
    HeadlessExecutor,
    LoadReport,
    LoadResult,
    MergeFailedStep,
    MergeState,
    MigrationService,
    OutputFormat,
    RecipeRepository,
    RecipeSource,
    RestartScope,
    RetryReason,
    SessionOutcome,
    Severity,
    SkillResult,
    SkillSource,
    SubprocessResult,
    SubprocessRunner,
    TerminationReason,
    TestRunner,
    TokenStore,
    WorkspaceManager,
    truncate_text,
)

__all__ = [
    # io
    "YAMLError",
    "_atomic_write",
    "dump_yaml_str",
    "ensure_project_temp",
    "load_yaml",
    # logging
    "configure_logging",
    "get_logger",
    # paths
    "GENERATED_FILES",
    "claude_code_log_path",
    "claude_code_project_dir",
    "is_git_worktree",
    "pkg_root",
    # types
    "AUTOSKILLIT_INSTALLED_VERSION",
    "AUTOSKILLIT_SKILL_PREFIX",
    "CONTEXT_EXHAUSTION_MARKER",
    "GATED_TOOLS",
    "PIPELINE_FORBIDDEN_TOOLS",
    "RESERVED_LOG_RECORD_KEYS",
    "SKILL_COMMAND_PREFIX",
    "SKILL_TOOLS",
    "UNGATED_TOOLS",
    "AuditStore",
    "ChannelConfirmation",
    "CleanupResult",
    "CloneManager",
    "DatabaseReader",
    "FailureRecord",
    "GatePolicy",
    "GitHubFetcher",
    "HeadlessExecutor",
    "LoadReport",
    "LoadResult",
    "MergeFailedStep",
    "MergeState",
    "MigrationService",
    "OutputFormat",
    "RecipeRepository",
    "RecipeSource",
    "RestartScope",
    "RetryReason",
    "SessionOutcome",
    "Severity",
    "SkillResult",
    "SkillSource",
    "SubprocessResult",
    "SubprocessRunner",
    "TerminationReason",
    "TestRunner",
    "TokenStore",
    "WorkspaceManager",
    "truncate_text",
]
