"""AutoSkillit-owned exec-time entrypoint shim.

Rendered to ``~/.local/bin/autoskillit`` by the install/update machinery,
replacing uv's own generated console-script wrapper. The shim resolves the
install-root generation selector exactly once, at exec time, then
``os.execv``s straight into the resolved incarnation's own entrypoint —
never re-consulting the selector afterward. This is what makes an
already-started process immune to a concurrent upgrade: the selector flip
that publishes a new generation cannot affect a process that has already
completed its own one-time resolution and handed control to the kernel's
``execve``.

Stdlib-only and version-independent by design: it is the one artifact that
must keep working across every future version, including versions that
haven't been written yet, so it cannot import ``autoskillit`` — the package
it exists to locate. ``hook_registry.py`` documents the same constraint for
hook dispatch subprocesses (see ``src/autoskillit/AGENTS.md``).

The generation-store path shape embedded in ``ENTRYPOINT_SHIM_SOURCE`` is duplicated,
not imported, from ``core._plugin_artifact_identity.generation_store_root``
/ ``generation_plugin_selector_path`` for exactly that reason — a bootstrap
shim cannot import the package it is trying to locate.
``tests/core/test_entrypoint_shim.py`` asserts the duplication stays in
sync with those functions' actual output for
``_AUTOSKILLIT_INSTALL_ROOT_KEY``.
"""

from __future__ import annotations

from pathlib import Path

from .io import atomic_write

ENTRYPOINT_SHIM_SOURCE = '''#!/usr/bin/env python3
"""AutoSkillit entrypoint shim - resolves once, execs, never re-consulted.

Generated by AutoSkillit. Do not edit by hand: edits are overwritten on the
next publish. Stdlib-only - this file must keep working across every future
autoskillit version, so it cannot import the autoskillit package itself.
"""
import os
import sys
from pathlib import Path
from typing import NoReturn

_SELECTOR = (
    Path.home()
    / ".autoskillit"
    / "plugin-generations"
    / "autoskillit-install"
    / "current"
)


def _die(message: str) -> NoReturn:
    sys.stderr.write(f"autoskillit: {message}\\n")
    sys.exit(1)


def main() -> None:
    if not _SELECTOR.is_symlink():
        _die(
            f"no install-root generation selector at {_SELECTOR}. "
            "Reinstall via install.sh (stable) or 'task install-dev' (develop)."
        )
    try:
        generation_dir = _SELECTOR.resolve(strict=True)
    except OSError as exc:
        _die(f"could not resolve install-root generation selector: {exc}")
    if sys.platform == "win32":
        inner = generation_dir / "autoskillit" / "Scripts" / "autoskillit.exe"
    else:
        inner = generation_dir / "autoskillit" / "bin" / "autoskillit"
    if not os.access(inner, os.X_OK):
        _die(f"resolved install-root generation has no executable entrypoint: {inner}")
    os.execv(str(inner), [str(inner), *sys.argv[1:]])


if __name__ == "__main__":
    main()
'''


def entrypoint_shim_path(home: Path) -> Path:
    """Return the well-known shim install location."""
    return Path(home) / ".local" / "bin" / "autoskillit"


def write_entrypoint_shim(home: Path) -> None:
    """Idempotently (re)write the shim at its well-known location.

    Writes via ``atomic_write()`` (temp-file + ``os.replace`` + fsync) so a
    concurrently exec'ing reader never observes a partially written shim.
    """
    path = entrypoint_shim_path(home)
    source = ENTRYPOINT_SHIM_SOURCE
    try:
        existing = path.read_text()
    except FileNotFoundError:
        existing = None
    if existing == source:
        return
    atomic_write(path, source, strict_durability=True)
    path.chmod(0o755)
