"""Backward-compat shim for _retiring_cache — see core.plugins._retiring_cache."""

from autoskillit.core.plugins._retiring_cache import (
    _RETIRING_CACHE_SCHEMA_VERSION,
    _classify_legacy_path,
    _install_lock_path,
    _InstallLock,
    _legacy_record_id,
    _next_corrupt_sidecar_path,
    _open_lock,
    _parse_utc,
    _record_from_json,
    _record_to_json,
    _retirement_intent,
    _retirement_staging_path,
    _retiring_cache_lock,
    _retiring_cache_path,
    _salvage_retiring_records,
    _write_retiring_cache_unlocked,
    append_retiring_record,
    due_retiring_records,
    is_reclaimable_artifact_path,
    migrate_retiring_cache_v1,
    read_retiring_cache,
    remove_retiring_records,
    repair_corrupt_retiring_cache,
)

__all__ = [
    "_RETIRING_CACHE_SCHEMA_VERSION",
    "_InstallLock",
    "_classify_legacy_path",
    "_install_lock_path",
    "_legacy_record_id",
    "_next_corrupt_sidecar_path",
    "_open_lock",
    "_parse_utc",
    "_record_from_json",
    "_record_to_json",
    "_retirement_intent",
    "_retirement_staging_path",
    "_retiring_cache_lock",
    "_retiring_cache_path",
    "_salvage_retiring_records",
    "_write_retiring_cache_unlocked",
    "append_retiring_record",
    "due_retiring_records",
    "is_reclaimable_artifact_path",
    "migrate_retiring_cache_v1",
    "read_retiring_cache",
    "remove_retiring_records",
    "repair_corrupt_retiring_cache",
]
