"""Backward-compat shim for agent_definition — see core.plugins.agent_definition."""

from autoskillit.core.plugins.agent_definition import (
    AGENT_DEFINITION_DIGEST_DOMAIN,
    AGENT_PROVISIONING_BASELINE,
    AGENT_PROVISIONING_SKILL_DERIVED,
    BUNDLED_EXPLORER_ROLES,
    CODEX_DISABLED_WEB_SEARCH_POLICY,
    CODEX_EXPLORER_IDENTITY,
    REPOSITORY_IMPACT_PROFILER_ROLE,
    SEMANTIC_CODE_NAVIGATOR_ROLE,
    WEB_EVIDENCE_RESEARCHER_ROLE,
    AgentDef,
    AgentDefinitionError,
    CodexAgentProjectionDef,
    agent_definition_digest,
    canonical_reader_tools_to_bare,
    load_agent_definition,
    load_agent_definitions,
    load_bundled_agent_definitions,
    normalize_codex_cli_version,
)

__all__ = [
    "AGENT_DEFINITION_DIGEST_DOMAIN",
    "AGENT_PROVISIONING_BASELINE",
    "AGENT_PROVISIONING_SKILL_DERIVED",
    "BUNDLED_EXPLORER_ROLES",
    "CODEX_DISABLED_WEB_SEARCH_POLICY",
    "CODEX_EXPLORER_IDENTITY",
    "REPOSITORY_IMPACT_PROFILER_ROLE",
    "SEMANTIC_CODE_NAVIGATOR_ROLE",
    "WEB_EVIDENCE_RESEARCHER_ROLE",
    "AgentDef",
    "AgentDefinitionError",
    "CodexAgentProjectionDef",
    "agent_definition_digest",
    "canonical_reader_tools_to_bare",
    "load_agent_definition",
    "load_agent_definitions",
    "load_bundled_agent_definitions",
    "normalize_codex_cli_version",
]
