"""Backward-compat shim for tool_sequence_analysis — see core.pipeline.tool_sequence_analysis."""

from autoskillit.core.pipeline.tool_sequence_analysis import (
    DFG,
    AnalysisResult,
    AssistantTurn,
    GapStats,
    TurnSequence,
    build_dfg,
    build_dfg_by_recipe,
    compute_analysis,
    compute_gap_stats,
    filter_sessions_by_recipe,
    format_top_bigrams,
    iter_merged_assistant_turns,
    parse_raw_cc_jsonl,
    parse_sessions_from_summary_dir,
    render_adjacency_table,
    render_dot,
    render_mermaid,
)

__all__ = [
    "AnalysisResult",
    "AssistantTurn",
    "DFG",
    "GapStats",
    "TurnSequence",
    "build_dfg",
    "build_dfg_by_recipe",
    "compute_analysis",
    "compute_gap_stats",
    "filter_sessions_by_recipe",
    "format_top_bigrams",
    "iter_merged_assistant_turns",
    "parse_raw_cc_jsonl",
    "parse_sessions_from_summary_dir",
    "render_adjacency_table",
    "render_dot",
    "render_mermaid",
]
