"""Fail-closed, observational repository collector implementations."""

from ._bounded import (
    BoundedCommandResult,
    CollectorLimits,
    CollectorSafetyError,
    list_contained_files,
    read_contained_file,
    resolve_contained_path,
    run_bounded_rg,
)
from .extractors import (
    COLLECTOR_PROFILES,
    CollectorProfile,
    collect_architecture,
    collect_artifact,
    collect_autoskillit_registry,
    collect_autoskillit_toml,
    collect_coverage_observation,
    collect_file_list,
    collect_generated_artifact,
    collect_python_ast,
    collect_python_stub,
    collect_search,
    collect_test_map_observation,
    collect_unsupported,
    collector_manifest_digest,
)

__all__ = [
    "BoundedCommandResult",
    "COLLECTOR_PROFILES",
    "CollectorLimits",
    "CollectorProfile",
    "CollectorSafetyError",
    "list_contained_files",
    "read_contained_file",
    "resolve_contained_path",
    "run_bounded_rg",
    "collect_artifact",
    "collect_architecture",
    "collect_autoskillit_registry",
    "collect_autoskillit_toml",
    "collect_coverage_observation",
    "collect_file_list",
    "collect_generated_artifact",
    "collect_python_ast",
    "collect_python_stub",
    "collect_search",
    "collect_test_map_observation",
    "collect_unsupported",
    "collector_manifest_digest",
]
