"""Generated hook-session-scope table. Do not edit manually.

Run `task sync-hook-scope-table` after changing HOOK_REGISTRY.
"""

HOOK_SCOPE_BY_SCRIPT: dict[str, str] = {
    "capture_lifecycle_hook.py": "any",
    "formatters/pretty_output_hook.py": "any",
    "guards/artifact_download_guard.py": "any",
    "guards/ask_user_question_guard.py": "headless_only",
    "guards/auto_compact_guard.py": "any",
    "guards/background_exec_guard.py": "any",
    "guards/branch_protection_guard.py": "any",
    "guards/compose_pr_body_guard.py": "headless_only",
    "guards/exploration_request_identity_guard.py": "interactive_only",
    "guards/fabricated_completion_guard.py": "any",
    "guards/fleet_claim_guard.py": "any",
    "guards/fleet_dispatch_guard.py": "any",
    "guards/generated_file_write_guard.py": "any",
    "guards/git_ops_guard.py": "any",
    "guards/github_mutation_guard.py": "any",
    "guards/grep_pattern_lint_guard.py": "any",
    "guards/ingredient_lock_guard.py": "any",
    "guards/installation_integrity_guard.py": "any",
    "guards/join_claim_guard.py": "any",
    "guards/join_followup_guard.py": "any",
    "guards/join_settle_guard.py": "any",
    "guards/join_stop_guard.py": "any",
    "guards/mcp_health_advisor.py": "interactive_only",
    "guards/open_kitchen_guard.py": "any",
    "guards/pipeline_step_guard.py": "any",
    "guards/planner_gh_discovery_guard.py": "headless_only",
    "guards/planner_result_naming_guard.py": "headless_only",
    "guards/pr_create_guard.py": "any",
    "guards/quota_guard.py": "any",
    "guards/recipe_read_guard.py": "headless_only",
    "guards/recipe_write_advisor.py": "interactive_only",
    "guards/remove_clone_guard.py": "any",
    "guards/reset_resume_gate.py": "any",
    "guards/resource_exhaustion_guard.py": "any",
    "guards/resume_ownership_guard.py": "any",
    "guards/review_loop_gate.py": "any",
    "guards/skill_cmd_guard.py": "any",
    "guards/skill_command_guard.py": "any",
    "guards/skill_load_guard.py": "headless_only",
    "guards/skill_orchestration_guard.py": "headless_only",
    "guards/test_runner_guard.py": "headless_only",
    "guards/unsafe_install_guard.py": "any",
    "guards/write_guard.py": "any",
    "lifecycle/child_outcome_hook.py": "any",
    "lint_after_edit_hook.py": "headless_only",
    "quota_guard_state_post_hook.py": "any",
    "quota_post_hook.py": "any",
    "recipe_confirmed_post_hook.py": "any",
    "resume_gate_post_hook.py": "any",
    "review_gate_post_hook.py": "any",
    "session_start_hook.py": "interactive_only",
    "shell_capture_hook.py": "any",
    "skill_load_post_hook.py": "any",
    "token_summary_hook.py": "any",
}
