"""Backward-compat shim for ``recipe/_api_orchestration.py``.

Real implementation: ``autoskillit.recipe.api_orchestration._api_orchestration`` (#4951).
Preserves old import path ``autoskillit.recipe._api_orchestration``.
"""

from __future__ import annotations

from autoskillit.recipe.api_orchestration._api_orchestration import (  # noqa: F401
    TYPE_CHECKING,
    LoadRecipeResult,
    Path,
    Sequence,
    _assemble_load_result,
    _build_orchestration_rules,
    _build_stop_step_semantics,
    _canonical_string_map,
    _finalize_recipe_steps,
    _infer_stop_failure,
    _LoadPipelineInputs,
    _parse_and_compose,
    _parse_recipe,
    _record_pipeline_error,
    _resolve_cache_inputs,
    _resolve_recipe_match,
    _run_validation_pipeline,
    _t,
    _ValidationResult,
    annotations,
    check_contract_staleness,
    compute_recipe_validity,
    findings_to_dicts,
    get_logger,
    list_recipes,
    load_and_validate,
    load_recipe_card,
    load_recipe_dict_with_declarations,
    logger,
    pkg_root,
    run_semantic_rules,
    time,
    validate_recipe_cards,
    validate_recipe_structure,
)

__all__ = [
    "_LoadPipelineInputs",
    "_ValidationResult",
    "_resolve_cache_inputs",
    "_resolve_recipe_match",
    "_parse_and_compose",
    "_run_validation_pipeline",
    "_assemble_load_result",
    "_finalize_recipe_steps",
    "_record_pipeline_error",
    "_infer_stop_failure",
    "_build_stop_step_semantics",
    "_build_orchestration_rules",
    "_canonical_string_map",
    "load_recipe_dict_with_declarations",
    "_parse_recipe",
    "load_recipe_card",
    "run_semantic_rules",
    "validate_recipe_structure",
    "list_recipes",
    "validate_recipe_cards",
    "check_contract_staleness",
    "compute_recipe_validity",
    "findings_to_dicts",
    "pkg_root",
    "_t",
    "logger",
    "load_and_validate",
]
