"""Backward-compat shim for ``recipe/_cmd_rpc_guards.py``.

Real implementation: ``autoskillit.recipe.cmd_rpc._cmd_rpc_guards`` (#4671 D).
Preserves old import path ``autoskillit.recipe._cmd_rpc_guards``.
"""

from __future__ import annotations

from autoskillit.recipe.cmd_rpc._cmd_rpc_guards import (
    _MAX_ASSOCIATION_FILES,
    _PLAN_ASSOCIATION_DOMAIN,
    _PLAN_ASSOCIATION_KEYS,
    AUDIT_CYCLE_SCHEMA_VERSION,
    ArtifactRef,
    AuditCycleVerifier,
    AuditVerdict,
    CommittedDispositionResolver,
    Path,
    StrEnum,
    _check_regression,
    _count_lines_in_files,
    _count_numstat_net,
    _log_plan_disposition_rejection,
    _normalize_plan_parts,
    _parse_numstat_per_file,
    _RegressionVerdict,
    _resolve_plan_disposition,
    annotations,
    atomic_write,
    check_dropped_ci_loop,
    check_dropped_healthy_loop,
    check_eject_limit,
    commit_guard,
    compute_branch,
    compute_canonical_hash,
    date,
    decode_versioned_json_bytes,
    get_logger,
    is_generated_path,
    logger,
    main_repo_guard,
    read_stable_contained_bytes,
    run_git,
    verify_plan_artifacts,
)

__all__ = [
    "AUDIT_CYCLE_SCHEMA_VERSION",
    "ArtifactRef",
    "AuditCycleVerifier",
    "AuditVerdict",
    "CommittedDispositionResolver",
    "Path",
    "StrEnum",
    "_MAX_ASSOCIATION_FILES",
    "_PLAN_ASSOCIATION_DOMAIN",
    "_PLAN_ASSOCIATION_KEYS",
    "_RegressionVerdict",
    "_check_regression",
    "_count_lines_in_files",
    "_count_numstat_net",
    "_log_plan_disposition_rejection",
    "_normalize_plan_parts",
    "_parse_numstat_per_file",
    "_resolve_plan_disposition",
    "annotations",
    "atomic_write",
    "check_dropped_ci_loop",
    "check_dropped_healthy_loop",
    "check_eject_limit",
    "commit_guard",
    "compute_branch",
    "compute_canonical_hash",
    "date",
    "decode_versioned_json_bytes",
    "get_logger",
    "is_generated_path",
    "logger",
    "main_repo_guard",
    "read_stable_contained_bytes",
    "run_git",
    "verify_plan_artifacts",
]
