"""Backward-compat shim for ``recipe/_io_loading.py``.

Real implementation: ``autoskillit.recipe.helpers._io_loading`` (#4671 D).
Preserves old import path ``autoskillit.recipe._io_loading``.
"""

from __future__ import annotations

from autoskillit.recipe.helpers._io_loading import (
    _SCRIPTS_PLACEHOLDER,
    _TEMP_PLACEHOLDER,
    INPUT_REF_RE,
    NON_RECIPE_DIRS,
    RECIPE_SCAN_DIRS,
    S_ISDIR,
    Any,
    Iterable,
    LoadReport,
    LoadResult,
    Path,
    Protocol,
    PurePosixPath,
    Recipe,
    RecipeInfo,
    RecipeSource,
    _cached_recipe_candidates,
    _cached_recipe_collection,
    _CachedRecipeCollection,
    _CandidateCollector,
    _CandidateEnumerator,
    _collect_recipes_from_candidates,
    _collect_relative_recipe_candidates,
    _DirectorySignature,
    _discover_recipe_collection,
    _enumerate_candidates_in_scan_dirs,
    _parse_recipe_candidate,
    _recipe_directory_signature,
    _recipe_input_signature,
    _RecipeInputSignature,
    _RecipeParser,
    _substitute_recipe_values,
    annotations,
    assert_no_raw_placeholders,
    clear_recipe_discovery_caches,
    fast_loads,
    get_logger,
    is_recipe_scan_path,
    load_recipe_dict,
    load_recipe_dict_with_declarations,
    load_yaml,
    logger,
    lru_cache,
    pkg_root,
    substitute_scripts_placeholder,
    substitute_temp_placeholder,
)

__all__ = [
    "Any",
    "INPUT_REF_RE",
    "Iterable",
    "LoadReport",
    "LoadResult",
    "NON_RECIPE_DIRS",
    "Path",
    "Protocol",
    "PurePosixPath",
    "RECIPE_SCAN_DIRS",
    "Recipe",
    "RecipeInfo",
    "RecipeSource",
    "S_ISDIR",
    "_CachedRecipeCollection",
    "_CandidateCollector",
    "_CandidateEnumerator",
    "_DirectorySignature",
    "_RecipeInputSignature",
    "_RecipeParser",
    "_SCRIPTS_PLACEHOLDER",
    "_TEMP_PLACEHOLDER",
    "_cached_recipe_candidates",
    "_cached_recipe_collection",
    "_collect_recipes_from_candidates",
    "_collect_relative_recipe_candidates",
    "_discover_recipe_collection",
    "_enumerate_candidates_in_scan_dirs",
    "_parse_recipe_candidate",
    "_recipe_directory_signature",
    "_recipe_input_signature",
    "_substitute_recipe_values",
    "annotations",
    "assert_no_raw_placeholders",
    "clear_recipe_discovery_caches",
    "fast_loads",
    "get_logger",
    "is_recipe_scan_path",
    "load_recipe_dict",
    "load_recipe_dict_with_declarations",
    "load_yaml",
    "logger",
    "lru_cache",
    "pkg_root",
    "substitute_scripts_placeholder",
    "substitute_temp_placeholder",
]
