"""Backward-compat shim for ``recipe/_recipe_composition.py``.

Real implementation: ``autoskillit.recipe.ingredients._recipe_composition`` (#4671 D).
Preserves old import path ``autoskillit.recipe._recipe_composition``.
"""

from __future__ import annotations

from autoskillit.recipe.ingredients._recipe_composition import (
    _MODEL_COND_RE,
    FALSY_STRINGS,
    INPUT_REF_RE,
    RECIPE_TERMINAL_TARGETS,
    SKILL_TOOLS,
    Any,
    NamedTuple,
    Path,
    Recipe,
    RecipeFlowEdge,
    RecipeStep,
    RouteEdge,
    StepResultCondition,
    StepResultRoute,
    YAMLError,
    _analysis_edges_from_effective_routes,
    _assert_content_integrity,
    _build_active_recipe,
    _collect_all_route_targets,
    _declared_route_signatures,
    _DeferredGuardState,
    _derive_rate_limit_routes,
    _drop_sub_recipe_step,
    _effective_routing_edges,
    _effective_routing_target_errors,
    _effective_step_graph,
    _extract_routing_edges,
    _is_ingredient_truthy,
    _load_recipe_from_path,
    _merge_sub_recipe,
    _move_step_to_front,
    _parse_recipe,
    _prune_skipped_steps,
    _resolve_hidden_inputs_in_content,
    _resolve_skip_redirects,
    _rewrite_step_routes,
    _step_block_pattern,
    _strip_step_block,
    _sweep_unreachable_steps,
    _validate_effective_graph_closure,
    _validate_no_dangling_routes,
    _validate_post_sweep_effective_graph,
    _validate_route_consistency,
    annotations,
    bfs_reachable,
    find_sub_recipe_by_name,
    load_yaml,
)

__all__ = [
    "Any",
    "FALSY_STRINGS",
    "INPUT_REF_RE",
    "NamedTuple",
    "Path",
    "RECIPE_TERMINAL_TARGETS",
    "Recipe",
    "RecipeFlowEdge",
    "RecipeStep",
    "RouteEdge",
    "SKILL_TOOLS",
    "StepResultCondition",
    "StepResultRoute",
    "YAMLError",
    "_DeferredGuardState",
    "_MODEL_COND_RE",
    "_analysis_edges_from_effective_routes",
    "_assert_content_integrity",
    "_build_active_recipe",
    "_collect_all_route_targets",
    "_declared_route_signatures",
    "_derive_rate_limit_routes",
    "_drop_sub_recipe_step",
    "_effective_routing_edges",
    "_effective_routing_target_errors",
    "_effective_step_graph",
    "_extract_routing_edges",
    "_is_ingredient_truthy",
    "_load_recipe_from_path",
    "_merge_sub_recipe",
    "_move_step_to_front",
    "_parse_recipe",
    "_prune_skipped_steps",
    "_resolve_hidden_inputs_in_content",
    "_resolve_skip_redirects",
    "_rewrite_step_routes",
    "_step_block_pattern",
    "_strip_step_block",
    "_sweep_unreachable_steps",
    "_validate_effective_graph_closure",
    "_validate_no_dangling_routes",
    "_validate_post_sweep_effective_graph",
    "_validate_route_consistency",
    "annotations",
    "bfs_reachable",
    "find_sub_recipe_by_name",
    "load_yaml",
]
