"""Backward-compat shim for ``recipe/contracts.py``.

Real implementation: ``autoskillit.recipe.contracts.contracts`` (#4671 D).
Preserves old import path ``autoskillit.recipe.contracts``.
"""

from __future__ import annotations

from autoskillit.recipe.contracts.contracts import (
    _CONTEXT_REF_RE,
    _TEMPLATE_REF_RE,
    INPUT_REF_RE,
    RESULT_CAPTURE_RE,
    AuditAuthorityPublicationSpec,
    AuditOutputContract,
    AuditOutputMode,
    BlockFingerprint,
    DataFlowEntry,
    OutcomeInvariantEntry,
    RecipeCard,
    ResultFieldSpec,
    SkillContract,
    SkillInput,
    SkillOutput,
    StaleItem,
    SuccessQualifierEntry,
    ToolOutputContractSpec,
    ToolOutputFieldSpec,
    _generate_recipe_card_for_recipe,
    check_contract_staleness,
    classify_step_arg_style,
    compute_skill_hash,
    count_positional_args,
    extract_context_refs,
    extract_input_refs,
    extract_skill_cmd_refs,
    generate_recipe_card,
    get_callable_contract,
    get_skill_contract,
    get_tool_output_contract,
    load_bundled_manifest,
    load_recipe_card,
    resolve_input_specs,
    resolve_skill_name,
    select_audit_output_contract,
    stale_to_suggestions,
    validate_recipe_cards,
)

__all__ = [
    "AuditAuthorityPublicationSpec",
    "AuditOutputContract",
    "AuditOutputMode",
    "BlockFingerprint",
    "DataFlowEntry",
    "INPUT_REF_RE",
    "OutcomeInvariantEntry",
    "RESULT_CAPTURE_RE",
    "RecipeCard",
    "ResultFieldSpec",
    "SkillContract",
    "SkillInput",
    "SkillOutput",
    "StaleItem",
    "SuccessQualifierEntry",
    "ToolOutputContractSpec",
    "ToolOutputFieldSpec",
    "_CONTEXT_REF_RE",
    "_TEMPLATE_REF_RE",
    "_generate_recipe_card_for_recipe",
    "check_contract_staleness",
    "classify_step_arg_style",
    "compute_skill_hash",
    "count_positional_args",
    "extract_context_refs",
    "extract_input_refs",
    "extract_skill_cmd_refs",
    "generate_recipe_card",
    "get_callable_contract",
    "get_skill_contract",
    "get_tool_output_contract",
    "load_bundled_manifest",
    "load_recipe_card",
    "resolve_input_specs",
    "resolve_skill_name",
    "select_audit_output_contract",
    "stale_to_suggestions",
    "validate_recipe_cards",
]
