"""Freshness tests for the generated core/__init__.pyi.

The stub is generated by scripts/generate_core_stub.py from each core source
module's __all__. A stale stub hides new symbols from lazy_loader (ImportError at
runtime) or keeps removed ones in the gateway, so the committed stub must equal
the generator's output.
"""

from __future__ import annotations

import ast
import importlib.util
from types import ModuleType

import pytest

from tests.arch._helpers import SRC_ROOT

pytestmark = [pytest.mark.layer("arch"), pytest.mark.small]

_CORE_DIR = SRC_ROOT / "core"


def test_cook_lifecycle_contracts_are_explicitly_exported_by_stub() -> None:
    pyi_path = _CORE_DIR / "__init__.pyi"
    tree = ast.parse(pyi_path.read_text(encoding="utf-8"), filename=str(pyi_path))
    imported = {
        alias.name
        for node in tree.body
        if isinstance(node, ast.ImportFrom)
        for alias in node.names
    }
    assert {
        "SessionAttemptHandle",
        "HookTrustPolicy",
        "ManagedSessionHome",
        "SessionSummary",
    } <= imported


@pytest.mark.medium
def test_core_stub_matches_generator() -> None:
    """core/__init__.pyi must equal the stub rendered from source-module __all__."""
    violations = _load_generator().check()
    assert violations == [], "\n".join(violations)


def _load_generator() -> ModuleType:
    script = SRC_ROOT.parent.parent / "scripts" / "generate_core_stub.py"
    spec = importlib.util.spec_from_file_location("generate_core_stub", script)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
