"""Tests that generated files with machine-local paths are not tracked in git."""

import re
from pathlib import Path

import pytest

from autoskillit.core.paths import GENERATED_FILES, is_generated_path
from tests._git_inventory import git_ls_files

pytestmark = [pytest.mark.layer("infra"), pytest.mark.medium]

REPO_ROOT = Path(__file__).parent.parent.parent


def _tracked_files() -> set[str]:
    return set(git_ls_files(REPO_ROOT, allow_empty=True))


def test_generated_files_importable_from_core_paths():
    """GENERATED_FILES is importable from autoskillit.core.paths and is a frozenset[str]."""
    assert isinstance(GENERATED_FILES, frozenset)
    assert len(GENERATED_FILES) > 0
    for entry in GENERATED_FILES:
        assert isinstance(entry, str)


def test_no_generated_files_tracked():
    """Generated config and diagram files must not be tracked in git."""
    tracked = _tracked_files()

    def _tracked_for_entry(entry: str) -> list[str]:
        if entry.endswith("/"):
            return [f for f in tracked if f.startswith(entry)]
        return [entry] if entry in tracked else []

    tracked_generated = [f for entry in GENERATED_FILES for f in _tracked_for_entry(entry)]
    assert tracked_generated == [], (
        f"Generated files must not be tracked in git: {tracked_generated}. "
        "Run 'git rm --cached <file>' and ensure the path is in .gitignore."
    )


def test_tracked_files_allows_empty_git_inventory(monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[tuple[Path, tuple[str, ...], bool]] = []

    def fake_git_ls_files(
        repo_root: Path, *pathspecs: str, allow_empty: bool = False
    ) -> tuple[str, ...]:
        calls.append((repo_root, pathspecs, allow_empty))
        return ()

    monkeypatch.setitem(globals(), "git_ls_files", fake_git_ls_files)

    assert _tracked_files() == set()
    assert calls == [(REPO_ROOT, (), True)]


def test_tracked_files_propagates_git_inventory_failure(monkeypatch: pytest.MonkeyPatch) -> None:
    def raise_git_inventory_failure(*args: object, **kwargs: object) -> tuple[str, ...]:
        raise RuntimeError("git ls-files failed")

    monkeypatch.setitem(globals(), "git_ls_files", raise_git_inventory_failure)

    with pytest.raises(RuntimeError, match="git ls-files failed"):
        _tracked_files()


def test_gitignore_covers_generated_paths():
    """`.gitignore` must have patterns for all generated config files."""
    gitignore = (REPO_ROOT / ".gitignore").read_text()
    for path in GENERATED_FILES:
        assert path in gitignore, f"Missing .gitignore entry for generated file: {path}"


def test_generated_files_covers_precommit_pattern():
    """Every entry in GENERATED_FILES must match the no-generated-configs pre-commit pattern."""
    config_text = (REPO_ROOT / ".pre-commit-config.yaml").read_text()
    # Extract the files: pattern from the no-generated-configs hook
    match = re.search(r"id:\s*no-generated-configs.*?files:\s*'([^']+)'", config_text, re.DOTALL)
    assert match, "Could not find no-generated-configs hook with files: pattern"
    pattern = match.group(1)
    for path in GENERATED_FILES:
        assert re.search(pattern, path), (
            f"GENERATED_FILES entry {path!r} does not match "
            f"no-generated-configs pattern {pattern!r}"
        )


def test_generated_files_covers_all_build_outputs():
    """Every file produced by build scripts must be covered by GENERATED_FILES."""
    recipes_dir = REPO_ROOT / "src" / "autoskillit" / "recipes"

    # Contract cards (YAML + JSON) — regenerated by regen-contracts task at install time
    contract_files = list((recipes_dir / "contracts").rglob("*"))
    for f in contract_files:
        if f.is_file():
            rel = str(f.relative_to(REPO_ROOT))
            assert is_generated_path(rel), (
                f"Build output {rel} is not covered by GENERATED_FILES. "
                "Add an entry or directory prefix."
            )


def test_regen_contracts_is_idempotent(tmp_path):
    """Running regen-contracts twice must produce identical output (no mtime changes)."""
    from autoskillit.recipe.contracts import generate_recipe_card
    from autoskillit.recipe.io import builtin_recipes_dir

    recipes_dir = builtin_recipes_dir()
    # Test on one recipe
    yaml_paths = sorted(recipes_dir.glob("*.yaml"))
    assert yaml_paths, "No recipe YAML files found"

    test_yaml = yaml_paths[0]
    out_dir = tmp_path / "contracts"
    out_dir.mkdir()

    # First run
    generate_recipe_card(test_yaml, recipes_dir=out_dir)
    card1 = out_dir / "contracts" / f"{test_yaml.stem}.yaml"
    assert card1.exists(), f"Contract card not created: {card1}"
    content1 = card1.read_text()

    # Second run
    generate_recipe_card(test_yaml, recipes_dir=out_dir)
    content2 = card1.read_text()

    assert content1 == content2, (
        "regen_contracts is not idempotent: second run produced different content"
    )


def test_compile_recipes_is_idempotent(tmp_path):
    """Running compile_recipes twice must not modify any JSON files when content is unchanged."""
    import importlib.util
    import shutil

    spec = importlib.util.spec_from_file_location(
        "compile_recipes", REPO_ROOT / "scripts" / "compile_recipes.py"
    )
    assert spec is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    _compile_one = mod._compile_one

    from autoskillit.recipe.io import builtin_recipes_dir

    recipes_dir = builtin_recipes_dir()
    yaml_paths = sorted(recipes_dir.rglob("*.yaml"))
    assert yaml_paths, "No recipe YAML files found"

    src_yaml = yaml_paths[0]
    test_yaml = tmp_path / src_yaml.name
    shutil.copy2(src_yaml, test_yaml)
    json_path = test_yaml.with_suffix(".json")

    _compile_one(test_yaml)
    assert json_path.exists(), f"JSON not created: {json_path}"
    mtime1 = json_path.stat().st_mtime_ns

    _compile_one(test_yaml)
    mtime2 = json_path.stat().st_mtime_ns

    assert mtime1 == mtime2, "compile_recipes is not idempotent: second run modified JSON mtime"
