"""Projected plugin artifact lifecycle facade."""

from .._projection_cache import (
    PROJECTION_ARTIFACT_MANIFEST_SCHEMA_VERSION,
    PROJECTION_CACHE_KEY_EXCLUSIONS,
    ProjectedPluginRetirementOwner,
    ProjectionCacheKey,
    is_projected_asset,
    iter_public_plugin_asset_files,
    projected_artifact_lease_path,
    projected_artifact_manifest_path,
    projected_plugin_artifact_digest,
    prune_stale_projections,
    public_plugin_asset_digest,
    read_projected_plugin_identity,
)
from ._hook_repair import (
    PluginHookRepairOutcome,
    PluginHookRepairStatus,
    ProjectedArtifactHooksInvalid,
    repair_broken_plugin_cache_hooks,
    repair_broken_projection_hooks,
    validate_staged_plugin_hooks,
)
from .authority import (
    ProjectedPluginArtifactAuthority,
    StaleGeneratorError,
    assert_generator_process_fresh,
    project_default_plugin_authority,
    project_direct_install_authority,
)
from .materialization import (
    AgentSkillDocument,
    SkillProjectionContext,
    materialize_agent_skill_tree,
    materialize_sanitized_plugin_root,
    project_agent_skill_document,
    validate_sanitized_plugin_artifact,
    write_generated_hooks_json,
)

__all__ = [
    "AgentSkillDocument",
    "PROJECTION_ARTIFACT_MANIFEST_SCHEMA_VERSION",
    "PROJECTION_CACHE_KEY_EXCLUSIONS",
    "ProjectedPluginArtifactAuthority",
    "ProjectedPluginRetirementOwner",
    "ProjectionCacheKey",
    "PluginHookRepairOutcome",
    "PluginHookRepairStatus",
    "SkillProjectionContext",
    "is_projected_asset",
    "iter_public_plugin_asset_files",
    "materialize_agent_skill_tree",
    "materialize_sanitized_plugin_root",
    "project_agent_skill_document",
    "project_default_plugin_authority",
    "project_direct_install_authority",
    "projected_artifact_lease_path",
    "projected_artifact_manifest_path",
    "projected_plugin_artifact_digest",
    "prune_stale_projections",
    "public_plugin_asset_digest",
    "read_projected_plugin_identity",
    "repair_broken_plugin_cache_hooks",
    "repair_broken_projection_hooks",
    "ProjectedArtifactHooksInvalid",
    "validate_sanitized_plugin_artifact",
    "StaleGeneratorError",
    "assert_generator_process_fresh",
    "validate_staged_plugin_hooks",
    "write_generated_hooks_json",
]
