#!/usr/bin/env python3
"""Generate src/autoskillit/core/__init__.pyi from each core source module's __all__.

The stub is a derived artifact. Its inputs are the ``__all__`` of every module in
EXPORT_MODULES, the ``_PRIVATE_REEXPORTS`` name-to-module map in core/__init__.py,
and GATEWAY_WITHHELD. Sources are resolved statically by AST — importing
autoskillit.core would run lazy_loader.attach_stub against the stub being generated.

The locked ruff (isort fix, then format) owns the ordering and layout of the
rendered stub, the same authority the lint gate applies.

Write mode (default) regenerates the stub. ``--check`` exits 1 with the added and
removed symbols when the stub on disk differs from the rendered one.
"""

import ast
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = REPO_ROOT / "src" / "autoskillit" / "core"
STUB_PATH = CORE_DIR / "__init__.pyi"
RUFF = REPO_ROOT / ".venv" / "bin" / "ruff"
REGENERATE_COMMAND = "task sync-core-stub"
HEADER = (
    "# Generated by scripts/generate_core_stub.py from each core source module's __all__.\n"
    f"# Do not edit by hand — change the source module's __all__ and run: {REGENERATE_COMMAND}\n"
)

EXPORT_MODULES: tuple[str, ...] = (
    "._capacity",
    "._entrypoint_shim",
    "._install_binding",
    "._managed_worker_capacity",
    "._release_identity",
    ".audit.audit_cycle_verifier",
    ".audit.audit_semantic_codec",
    ".audit.closure_hashing",
    ".audit.closure_verifier",
    ".claude_env.claude_env",
    ".claude_env.conventions",
    ".claude_env.feature_flags",
    ".context_admission",
    ".fs_observation",
    ".git.branch_guard",
    ".git.git_refs",
    ".git.git_remote",
    ".git.github_url",
    ".git.test_gate_command",
    ".install.cmd_runner",
    ".install.install_detect",
    ".io",
    ".logging",
    ".pipeline._execution_marker",
    ".pipeline._step_context",
    ".pipeline.pipeline_tracker",
    ".planset",
    ".plugins._active_kitchens",
    ".plugins._plugin_artifact_identity",
    ".plugins._plugin_artifact_retirement",
    ".plugins._plugin_ids",
    ".plugins._retiring_cache",
    ".plugins.agent_definition",
    ".runtime._linux_proc",
    ".runtime._reclamation",
    ".runtime.artifact_lease",
    ".runtime.executable_binding",
    ".runtime.kitchen_state",
    ".runtime.private_file",
    ".runtime.readiness",
    ".runtime.session_provenance",
    ".runtime.session_registry",
    ".runtime.worktree_gate_lease",
    ".tool_registry",
    ".tool_sequence_analysis",
    ".types",
)

# Public names listed in a source module's __all__ that the root gateway deliberately
# does not export; consumers import them from their owning subpackage instead.
GATEWAY_WITHHELD: frozenset[str] = frozenset(
    {
        "ALLOCATION_KIND",
        "CLOSURE_ROW_ALLOWED_ASSESSMENTS",
        "CLOSURE_ROW_BLOCKING_ASSESSMENTS",
        "OutcomeInvariantSpec",
        "SessionIndexEntry",
        "TokenUsageFileEntry",
    }
)


class StubSourceError(Exception):
    """A core stub input cannot be resolved; the message names the offending source."""


def _module_path(rel: str, base: Path) -> Path:
    target = base.joinpath(*rel.lstrip(".").split("."))
    for candidate in (target / "__init__.py", target.with_suffix(".py")):
        if candidate.is_file():
            return candidate
    raise StubSourceError(f"{base}: cannot resolve module {rel!r}")


def _all_aliases(tree: ast.Module) -> dict[str, str]:
    return {
        alias.asname: "." * node.level + (node.module or "")
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom)
        for alias in node.names
        if alias.name == "__all__" and alias.asname
    }


def _assigned_value(stmt: ast.stmt, name: str) -> ast.expr | None:
    if isinstance(stmt, ast.Assign) and any(
        isinstance(t, ast.Name) and t.id == name for t in stmt.targets
    ):
        return stmt.value
    if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
        return stmt.value if stmt.target.id == name else None
    return None


def _find_all_value(tree: ast.Module) -> ast.expr | None:
    found: ast.expr | None = None
    for stmt in tree.body:
        for inner in [*stmt.body, *stmt.orelse] if isinstance(stmt, ast.If) else [stmt]:
            found = _assigned_value(inner, "__all__") or found
    return found


def _literal_names(value: ast.expr) -> list[str] | None:
    if not isinstance(value, (ast.List, ast.Tuple)):
        return None
    names = [
        elt.value
        for elt in value.elts
        if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
    ]
    return names if len(names) == len(value.elts) else None


def _sum_operands(value: ast.expr) -> list[ast.expr]:
    if isinstance(value, ast.BinOp) and isinstance(value.op, ast.Add):
        return [*_sum_operands(value.left), *_sum_operands(value.right)]
    return [value]


def _parse(path: Path) -> ast.Module:
    try:
        return ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (SyntaxError, UnicodeDecodeError, OSError) as exc:
        raise StubSourceError(f"{path}: could not parse — {exc}") from exc


def _resolve_all(path: Path, seen: frozenset[Path]) -> list[str]:
    if path in seen:
        raise StubSourceError(f"{path}: __all__ aggregation cycle")
    tree = _parse(path)
    value = _find_all_value(tree)
    literal = _literal_names(value) if value is not None else None
    if literal is not None:
        return literal
    operands = _sum_operands(value) if isinstance(value, ast.BinOp) else []
    aliases = _all_aliases(tree)
    names = [o.id for o in operands if isinstance(o, ast.Name) and o.id in aliases]
    if not operands or len(names) != len(operands):
        raise StubSourceError(
            f"{path}: __all__ must be a literal list/tuple of str "
            "or a concatenation of imported __all__ aliases"
        )
    return [
        name
        for alias in names
        for name in _resolve_all(_module_path(aliases[alias], path.parent), seen | {path})
    ]


def _private_reexports() -> dict[str, str]:
    init_path = CORE_DIR / "__init__.py"
    node = next(
        (
            v
            for stmt in _parse(init_path).body
            if (v := _assigned_value(stmt, "_PRIVATE_REEXPORTS"))
        ),
        None,
    )
    if node is None:
        raise StubSourceError(f"{init_path}: _PRIVATE_REEXPORTS not found")
    try:
        value = ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError) as exc:
        raise StubSourceError(f"{init_path}: _PRIVATE_REEXPORTS is not a literal") from exc
    if isinstance(value, dict) and all(
        isinstance(k, str) and isinstance(v, str) for k, v in value.items()
    ):
        return value
    raise StubSourceError(f"{init_path}: _PRIVATE_REEXPORTS must be a literal dict[str, str]")


def _claim(exports: dict[str, str], name: str, module: str) -> None:
    owner = exports.setdefault(name, module)
    if owner != module:
        raise StubSourceError(f"{name} is exported by both {owner} and {module}")


def _public_exports() -> dict[str, str]:
    exports: dict[str, str] = {}
    for module in EXPORT_MODULES:
        for name in _resolve_all(_module_path(module, CORE_DIR), frozenset()):
            if not name.startswith("_"):
                _claim(exports, name, module)
    return exports


def collect_exports() -> dict[str, str]:
    """Return every stub name mapped to the relative module it is imported from."""
    exports = _public_exports()
    private = _private_reexports()
    unreached = sorted(GATEWAY_WITHHELD - exports.keys())
    if unreached:
        raise StubSourceError(f"GATEWAY_WITHHELD names reached by no export module: {unreached}")
    overlap = sorted(GATEWAY_WITHHELD & private.keys())
    if overlap:
        raise StubSourceError(f"GATEWAY_WITHHELD names also in _PRIVATE_REEXPORTS: {overlap}")
    for name in GATEWAY_WITHHELD:
        del exports[name]
    for name, module in private.items():
        _claim(exports, name, module)
    return exports


def _ruff(args: list[str], source: str) -> str:
    if not RUFF.is_file():
        raise StubSourceError(f"{RUFF} not found — run: task install-worktree")
    result = subprocess.run(
        [str(RUFF), *args],
        input=source,
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
        timeout=60,
        check=False,
    )
    if result.returncode != 0:
        raise StubSourceError(f"ruff {' '.join(args)} failed:\n{result.stderr}")
    return result.stdout


def render_stub() -> str:
    lines = "".join(
        f"from {module} import {name} as {name}\n" for name, module in collect_exports().items()
    )
    stdin_name = ["--stdin-filename", str(STUB_PATH), "-"]
    sorted_source = _ruff(["check", "--fix-only", "--select", "I", *stdin_name], HEADER + lines)
    formatted = _ruff(["format", *stdin_name], sorted_source)
    report = _ruff(
        ["check", "--select", "E501", "--exit-zero", "--output-format", "json", *stdin_name],
        formatted,
    )
    return _mark_long_lines(formatted, {d["location"]["row"] for d in json.loads(report)})


def _mark_long_lines(source: str, rows: set[int]) -> str:
    """Suppress E501 on long names, which the formatter cannot wrap further."""
    return "".join(
        f"{line.rstrip(chr(10))}  # noqa: E501\n" if number in rows else line
        for number, line in enumerate(source.splitlines(keepends=True), start=1)
    )


def _names(text: str) -> set[str]:
    return {
        alias.asname or alias.name
        for node in ast.walk(ast.parse(text))
        if isinstance(node, ast.ImportFrom)
        for alias in node.names
    }


def _stale_report(rendered: str, on_disk: str) -> str:
    rendered_names = _names(rendered)
    try:
        disk_names = _names(on_disk)
    except SyntaxError as exc:
        return (
            f"{STUB_PATH} is stale:\n"
            f"  invalid Python syntax at line {exc.lineno}: {exc.msg}\n"
            f"Regenerate with: {REGENERATE_COMMAND}"
        )
    lines = [f"{STUB_PATH} is stale:"]
    lines += [f"  + {name}" for name in sorted(rendered_names - disk_names)]
    lines += [f"  - {name}" for name in sorted(disk_names - rendered_names)]
    if rendered_names == disk_names:
        lines.append("  ordering/format only")
    lines.append(f"Regenerate with: {REGENERATE_COMMAND}")
    return "\n".join(lines)


def check() -> list[str]:
    """Return stub freshness violations as structured strings (empty when fresh)."""
    if not (CORE_DIR / "__init__.py").is_file() or not EXPORT_MODULES:
        return [f"{CORE_DIR}: no core export sources discovered"]
    try:
        rendered = render_stub()
    except StubSourceError as exc:
        return [str(exc)]
    on_disk = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.is_file() else ""
    if on_disk != rendered:
        return [_stale_report(rendered, on_disk)]
    return []


def _write() -> int:
    try:
        rendered = render_stub()
    except StubSourceError as exc:
        print(exc, file=sys.stderr)
        return 1
    if STUB_PATH.is_file() and STUB_PATH.read_text(encoding="utf-8") == rendered:
        print("core stub is fresh")
        return 0
    STUB_PATH.write_text(rendered, encoding="utf-8")
    print(f"regenerated {STUB_PATH}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if "--check" not in args:
        return _write()
    violations = check()
    for violation in violations:
        print(violation, file=sys.stderr)
    if violations:
        return 1
    print("core stub is fresh")
    return 0


if __name__ == "__main__":
    sys.exit(main())
