"""config/ IL-1 package: configuration loading with layered YAML resolution.

Re-exports the full public surface of config.settings so callers can use
either `from autoskillit.config import AutomationConfig` or the explicit
`from autoskillit.config.settings import AutomationConfig`.
"""

from autoskillit.config._config_dataclasses import (
    _MAX_CONCURRENT_DISPATCHES as _MAX_CONCURRENT_DISPATCHES,
)
from autoskillit.config.ingredient_defaults import (
    CONFIG_DEFAULT_INGREDIENTS,
    SERVER_AUTHORITATIVE_CONFIG_PATHS,
    SERVER_AUTHORITATIVE_INGREDIENTS,
    SERVER_AUTHORITATIVE_KEY_HINTS,
    apply_config_authoritative_overrides,
    build_config_authoritative_layer,
    build_config_default_layer,
    iter_display_categories,
    resolve_ingredient_defaults,
)
from autoskillit.config.settings import (
    _SECRETS_ONLY_KEYS as _SECRETS_ONLY_KEYS,
)
from autoskillit.config.settings import (
    RETIRED_CONFIG_KEYS,
    AgentBackendConfig,
    AutomationConfig,
    BranchingConfig,
    CIConfig,
    ClassifyFixConfig,
    ConfigSchemaError,
    CoreRunConfig,
    DiagnosticsConfig,
    FleetConfig,
    GitHubConfig,
    ImplementGateConfig,
    LinuxTracingConfig,
    LoggingConfig,
    McpResponseConfig,
    MigrationConfig,
    OutputBudgetConfig,
    PacksConfig,
    PlanConfig,
    ProviderProfileDef,
    ProvidersConfig,
    QuotaGuardConfig,
    ReadDbConfig,
    RemappedConfigKey,
    ReportBugConfig,
    ResetWorkspaceConfig,
    RetiredConfigKeyDef,
    ReviewConfig,
    RunSkillConfig,
    SafetyConfig,
    SkillsConfig,
    SubsetsConfig,
    TestCheckConfig,
    TokenUsageConfig,
    WorkspaceConfig,
    WorktreeSetupConfig,
    compute_codex_mcp_tool_timeout,
    load_config,
    remap_retired_keys,
    validate_layer_keys,
    write_config_layer,
)
from autoskillit.core import BACKEND_CAPABILITY_INGREDIENTS

__all__ = [
    "AgentBackendConfig",
    "AutomationConfig",
    "BranchingConfig",
    "ConfigSchemaError",
    "CIConfig",
    "ClassifyFixConfig",
    "CoreRunConfig",
    "DiagnosticsConfig",
    "FleetConfig",
    "GitHubConfig",
    "ImplementGateConfig",
    "LinuxTracingConfig",
    "LoggingConfig",
    "McpResponseConfig",
    "MigrationConfig",
    "OutputBudgetConfig",
    "PacksConfig",
    "ProviderProfileDef",
    "ProvidersConfig",
    "QuotaGuardConfig",
    "ReadDbConfig",
    "RemappedConfigKey",
    "ReportBugConfig",
    "ResetWorkspaceConfig",
    "RETIRED_CONFIG_KEYS",
    "RetiredConfigKeyDef",
    "ReviewConfig",
    "RunSkillConfig",
    "SafetyConfig",
    "SkillsConfig",
    "SubsetsConfig",
    "TestCheckConfig",
    "TokenUsageConfig",
    "WorkspaceConfig",
    "WorktreeSetupConfig",
    "PlanConfig",
    "compute_codex_mcp_tool_timeout",
    "iter_display_categories",
    "load_config",
    "remap_retired_keys",
    "resolve_ingredient_defaults",
    "BACKEND_CAPABILITY_INGREDIENTS",
    "CONFIG_DEFAULT_INGREDIENTS",
    "SERVER_AUTHORITATIVE_CONFIG_PATHS",
    "SERVER_AUTHORITATIVE_INGREDIENTS",
    "SERVER_AUTHORITATIVE_KEY_HINTS",
    "apply_config_authoritative_overrides",
    "build_config_authoritative_layer",
    "build_config_default_layer",
    "validate_layer_keys",
    "write_config_layer",
]
