"""Environment variable names, session type aliases, context markers, logging keys.

Zero autoskillit imports. Self-contained.
"""

from __future__ import annotations

from importlib.metadata import version

__all__ = [
    "AUTOSKILLIT_APPLICABLE_GUARDS",
    "AUTOSKILLIT_ATTESTED_CLIENT_GATE_TOKENS",
    "AUTOSKILLIT_ATTESTED_META_SUPPORT",
    "AUTOSKILLIT_INSTALLED_VERSION",
    "AUTOSKILLIT_PRIVATE_ENV_VARS",
    "AUTOSKILLIT_STATE_ROOT_ENV_VAR",
    "AUTOSKILLIT_WRITE_GUARD_TOOL_NAMES",
    "AUDIT_ADMISSION_AUTHORITY_PATH_ENV_VAR",
    "CLAUDE_MCP_CONNECTION_NONBLOCKING",
    "CLAUDE_MCP_CONNECT_TIMEOUT_ENV_VAR",
    "CLAUDE_MCP_CONNECT_TIMEOUT_MS",
    "CODEX_CONTEXT_EXHAUSTION_MARKER",
    "CODEX_SCHEMA_VERSION",
    "CONTEXT_EXHAUSTION_MARKER",
    "RESERVED_LOG_RECORD_KEYS",
    "SESSION_TYPE_ENV_VAR",
    "SESSION_TYPE_FLEET",
    "SESSION_TYPE_ORCHESTRATOR",
    "SESSION_TYPE_SKILL",
    "HEADLESS_ENV_VAR",
    "HEADLESS_AUTO_GATE_ENV_VAR",
    "FLEET_MODE_ENV_VAR",
    "FLEET_DISPATCH_MODE",
    "CAMPAIGN_ID_ENV_VAR",
    "DISPATCH_ID_ENV_VAR",
    "FLEET_INSPECTOR_MODEL_ENV_VAR",
    "KITCHEN_SESSION_ID_ENV_VAR",
    "LAUNCH_ID_ENV_VAR",
    "FOOD_TRUCK_TOOL_TAGS_ENV_VAR",
    "AGENT_BACKEND_DYNACONF_ENV_VAR",
    "AGENT_BACKEND_ENV_VAR",
    "AGENT_BACKEND_CLAUDE_CODE",
    "AGENT_BACKEND_CODEX",
    "PROVIDER_PROFILE_ENV_VAR",
    "MCP_CLIENT_BACKEND_ENV_VAR",
    "MANAGED_ATTEMPT_ID_ENV_VAR",
    "MANAGED_LAUNCH_ID_ENV_VAR",
    "MANAGED_LINEAGE_DIGEST_ENV_VAR",
    "MANAGED_LINEAGE_REF_ENV_VAR",
    "NATIVE_SHELL_CAPTURE_MODE_ENV_VAR",
    "FLEET_SESSION_REQUIRED_ENV",
    "SKILL_SESSION_REQUIRED_ENV",
    "ORCHESTRATOR_SESSION_REQUIRED_ENV",
    "ORDER_INTERACTIVE_REQUIRED_ENV",
    "RESUME_SESSION_BASELINE_KEYS",
    "CODEX_COOK_RESERVED_ENV_VARS",
    "CODEX_INTERACTIVE_REQUIRED_ENV",
    "CODEX_STARTUP_TRACE_ENV_VAR",
    "CODEX_MCP_ENV_FORWARD_VARS",
    "EVIDENCE_READER_AUTHORITY_ENV_VAR",
    "EVIDENCE_READER_CAPABILITY_ENV_VAR",
    "EVIDENCE_READER_AUTHORITY_PATH_ENV_VAR",
    "EVIDENCE_READER_ENV_FORWARD_VARS",
    "KNOWN_BACKEND_NAMES",
]

AUTOSKILLIT_INSTALLED_VERSION: str = version("autoskillit")
CODEX_SCHEMA_VERSION: int = 2
CLAUDE_MCP_CONNECTION_NONBLOCKING: str = "0"
CLAUDE_MCP_CONNECT_TIMEOUT_ENV_VAR: str = "MCP_CONNECT_TIMEOUT_MS"
CLAUDE_MCP_CONNECT_TIMEOUT_MS: int = 30_000

# Session type environment variable and valid values.
SESSION_TYPE_ENV_VAR: str = "AUTOSKILLIT_SESSION_TYPE"
SESSION_TYPE_ORCHESTRATOR: str = "orchestrator"
SESSION_TYPE_FLEET: str = "fleet"
SESSION_TYPE_SKILL: str = "skill"
HEADLESS_ENV_VAR: str = "AUTOSKILLIT_HEADLESS"
HEADLESS_AUTO_GATE_ENV_VAR: str = "AUTOSKILLIT_HEADLESS_AUTO_GATE"
CAMPAIGN_ID_ENV_VAR: str = "AUTOSKILLIT_CAMPAIGN_ID"
FLEET_MODE_ENV_VAR: str = "AUTOSKILLIT_FLEET_MODE"
FLEET_DISPATCH_MODE: str = "dispatch"
DISPATCH_ID_ENV_VAR: str = "AUTOSKILLIT_DISPATCH_ID"
FLEET_INSPECTOR_MODEL_ENV_VAR: str = "AUTOSKILLIT_FLEET_INSPECTOR_MODEL"
KITCHEN_SESSION_ID_ENV_VAR: str = "AUTOSKILLIT_KITCHEN_SESSION_ID"
LAUNCH_ID_ENV_VAR: str = "AUTOSKILLIT_LAUNCH_ID"
FOOD_TRUCK_TOOL_TAGS_ENV_VAR: str = "AUTOSKILLIT_FOOD_TRUCK_TOOL_TAGS"
AGENT_BACKEND_ENV_VAR: str = "AUTOSKILLIT_AGENT_BACKEND"
AGENT_BACKEND_DYNACONF_ENV_VAR: str = "AUTOSKILLIT_AGENT_BACKEND__BACKEND"
AGENT_BACKEND_CLAUDE_CODE: str = "claude-code"
AGENT_BACKEND_CODEX: str = "codex"
PROVIDER_PROFILE_ENV_VAR: str = "AUTOSKILLIT_PROVIDER_PROFILE"
CODEX_STARTUP_TRACE_ENV_VAR: str = "AUTOSKILLIT_CODEX_STARTUP_TRACE"
CODEX_COOK_RESERVED_ENV_VARS: frozenset[str] = frozenset({"CODEX_HOME", "CODEX_SQLITE_HOME"})
AUTOSKILLIT_APPLICABLE_GUARDS: str = "AUTOSKILLIT_APPLICABLE_GUARDS"
AUTOSKILLIT_WRITE_GUARD_TOOL_NAMES: str = "AUTOSKILLIT_WRITE_GUARD_TOOL_NAMES"
AUDIT_ADMISSION_AUTHORITY_PATH_ENV_VAR: str = "AUTOSKILLIT_AUDIT_ADMISSION_AUTHORITY_PATH"
# The orchestrating project root, injected by launch preparation so guards can
# locate `.autoskillit/` state in worktree topologies where the hook payload's
# own cwd points into a sibling worktree with its own checked-in `.autoskillit/`.
# Read as a bare string literal by hooks/_hook_payload.py's resolve_state_root
# (stdlib-only boundary prevents importing this constant there) — keep the two
# string values byte-identical.
AUTOSKILLIT_STATE_ROOT_ENV_VAR: str = "AUTOSKILLIT_STATE_ROOT"
# Launcher-to-server host client attestation transport. Injected by every
# command builder (SHARED_BASELINE_ENV) so the server can read, once at
# startup, the launcher's attested client capabilities without trusting
# per-call claims. Absent/malformed → conservative ENVELOPE default.
AUTOSKILLIT_ATTESTED_CLIENT_GATE_TOKENS: str = "AUTOSKILLIT_ATTESTED_CLIENT_GATE_TOKENS"
AUTOSKILLIT_ATTESTED_META_SUPPORT: str = "AUTOSKILLIT_ATTESTED_META_SUPPORT"
KNOWN_BACKEND_NAMES: frozenset[str] = frozenset({AGENT_BACKEND_CLAUDE_CODE, AGENT_BACKEND_CODEX})
MCP_CLIENT_BACKEND_ENV_VAR: str = "AUTOSKILLIT_MCP_CLIENT_BACKEND"
NATIVE_SHELL_CAPTURE_MODE_ENV_VAR: str = "AUTOSKILLIT_NATIVE_SHELL_CAPTURE_MODE"
MANAGED_LAUNCH_ID_ENV_VAR: str = "AUTOSKILLIT_MANAGED_LAUNCH_ID"
MANAGED_ATTEMPT_ID_ENV_VAR: str = "AUTOSKILLIT_MANAGED_ATTEMPT_ID"
MANAGED_LINEAGE_DIGEST_ENV_VAR: str = "AUTOSKILLIT_MANAGED_LINEAGE_DIGEST"
MANAGED_LINEAGE_REF_ENV_VAR: str = "AUTOSKILLIT_MANAGED_LINEAGE_REF"
EVIDENCE_READER_AUTHORITY_ENV_VAR: str = "AUTOSKILLIT_EVIDENCE_READER_AUTHORITY"
EVIDENCE_READER_CAPABILITY_ENV_VAR: str = "AUTOSKILLIT_EVIDENCE_READER_CAPABILITY"
EVIDENCE_READER_AUTHORITY_PATH_ENV_VAR: str = "AUTOSKILLIT_EVIDENCE_READER_AUTHORITY_PATH"
EVIDENCE_READER_ENV_FORWARD_VARS: frozenset[str] = frozenset(
    {
        EVIDENCE_READER_AUTHORITY_ENV_VAR,
        EVIDENCE_READER_CAPABILITY_ENV_VAR,
        EVIDENCE_READER_AUTHORITY_PATH_ENV_VAR,
    }
)

# Both AGENT_BACKEND_ENV_VAR (flat) and AGENT_BACKEND_DYNACONF_ENV_VAR
# (nested Dynaconf form) are scrubbed from ambient env by build_env(),
# then re-injected via extras in all cmd builders.  The nested form is
# additionally forwarded to the MCP server via CODEX_MCP_ENV_FORWARD_VARS
# in config.toml so Dynaconf resolves agent_backend.backend in the child.
AUTOSKILLIT_PRIVATE_ENV_VARS: frozenset[str] = frozenset(
    {
        HEADLESS_ENV_VAR,
        "AUTOSKILLIT_SKIP_STALE_CHECK",
        "AUTOSKILLIT_SKIP_UPDATE_CHECK",
        "AUTOSKILLIT_FORCE_UPDATE_CHECK",
        SESSION_TYPE_ENV_VAR,
        FLEET_MODE_ENV_VAR,
        CAMPAIGN_ID_ENV_VAR,
        DISPATCH_ID_ENV_VAR,
        FLEET_INSPECTOR_MODEL_ENV_VAR,
        KITCHEN_SESSION_ID_ENV_VAR,
        "AUTOSKILLIT_CAMPAIGN_STATE_PATH",
        "AUTOSKILLIT_PROJECT_DIR",
        FOOD_TRUCK_TOOL_TAGS_ENV_VAR,
        HEADLESS_AUTO_GATE_ENV_VAR,
        MCP_CLIENT_BACKEND_ENV_VAR,
        LAUNCH_ID_ENV_VAR,
        AUTOSKILLIT_APPLICABLE_GUARDS,
        AUTOSKILLIT_WRITE_GUARD_TOOL_NAMES,
        AUDIT_ADMISSION_AUTHORITY_PATH_ENV_VAR,
        "AUTOSKILLIT_SKILL_NAME",
        PROVIDER_PROFILE_ENV_VAR,
        "SCENARIO_STEP_NAME",
        "AUTOSKILLIT_ALLOWED_WRITE_PREFIX",
        "AUTOSKILLIT_ALLOWED_WRITE_PREFIXES",
        "AUTOSKILLIT_CWD",
        "MAX_MCP_OUTPUT_TOKENS",
        "AUTOSKILLIT_SESSION_DEADLINE",
        AGENT_BACKEND_ENV_VAR,
        AGENT_BACKEND_DYNACONF_ENV_VAR,
        CODEX_STARTUP_TRACE_ENV_VAR,
        NATIVE_SHELL_CAPTURE_MODE_ENV_VAR,
        AUTOSKILLIT_STATE_ROOT_ENV_VAR,
        MANAGED_LAUNCH_ID_ENV_VAR,
        MANAGED_ATTEMPT_ID_ENV_VAR,
        MANAGED_LINEAGE_DIGEST_ENV_VAR,
        MANAGED_LINEAGE_REF_ENV_VAR,
        *EVIDENCE_READER_ENV_FORWARD_VARS,
        AUTOSKILLIT_ATTESTED_CLIENT_GATE_TOKENS,
        AUTOSKILLIT_ATTESTED_META_SUPPORT,
        *CODEX_COOK_RESERVED_ENV_VARS,
    }
)

FLEET_SESSION_REQUIRED_ENV: frozenset[str] = frozenset(
    {
        SESSION_TYPE_ENV_VAR,
        FLEET_MODE_ENV_VAR,
        "AUTOSKILLIT_PROJECT_DIR",
        HEADLESS_ENV_VAR,
    }
)

SKILL_SESSION_REQUIRED_ENV: frozenset[str] = frozenset(
    {
        HEADLESS_ENV_VAR,
        SESSION_TYPE_ENV_VAR,
        "MAX_MCP_OUTPUT_TOKENS",
        "MCP_CONNECTION_NONBLOCKING",
        AGENT_BACKEND_ENV_VAR,
        AGENT_BACKEND_DYNACONF_ENV_VAR,
        AUTOSKILLIT_APPLICABLE_GUARDS,
    }
)

ORCHESTRATOR_SESSION_REQUIRED_ENV: frozenset[str] = frozenset(
    {
        HEADLESS_ENV_VAR,
        SESSION_TYPE_ENV_VAR,
        "MAX_MCP_OUTPUT_TOKENS",
        "MCP_CONNECTION_NONBLOCKING",
        AGENT_BACKEND_ENV_VAR,
        AGENT_BACKEND_DYNACONF_ENV_VAR,
    }
)

RESUME_SESSION_BASELINE_KEYS: frozenset[str] = frozenset(
    {
        "MAX_MCP_OUTPUT_TOKENS",
    }
)

# Interactive `autoskillit order` session contract. Deliberately omits
# HEADLESS_ENV_VAR (AUTOSKILLIT_HEADLESS) — interactive order sessions are not
# headless, unlike ORCHESTRATOR_SESSION_REQUIRED_ENV (the fleet/food-truck
# contract), so injecting it here would make every interactive launch fail
# required-key validation.
ORDER_INTERACTIVE_REQUIRED_ENV: frozenset[str] = frozenset(
    {
        SESSION_TYPE_ENV_VAR,
        "MAX_MCP_OUTPUT_TOKENS",
        "MCP_CONNECTION_NONBLOCKING",
        AGENT_BACKEND_ENV_VAR,
        AGENT_BACKEND_DYNACONF_ENV_VAR,
    }
)

CODEX_MCP_ENV_FORWARD_VARS: frozenset[str] = frozenset(
    {
        HEADLESS_ENV_VAR,
        HEADLESS_AUTO_GATE_ENV_VAR,
        MCP_CLIENT_BACKEND_ENV_VAR,
        SESSION_TYPE_ENV_VAR,
        FOOD_TRUCK_TOOL_TAGS_ENV_VAR,
        AGENT_BACKEND_DYNACONF_ENV_VAR,
        FLEET_INSPECTOR_MODEL_ENV_VAR,
        LAUNCH_ID_ENV_VAR,
        AUTOSKILLIT_STATE_ROOT_ENV_VAR,
        AUDIT_ADMISSION_AUTHORITY_PATH_ENV_VAR,
        "AUTOSKILLIT_SKILL_NAME",
    }
)

CODEX_INTERACTIVE_REQUIRED_ENV: frozenset[str] = frozenset(
    {
        MCP_CLIENT_BACKEND_ENV_VAR,
        AGENT_BACKEND_ENV_VAR,
        "MAX_MCP_OUTPUT_TOKENS",
    }
)

CONTEXT_EXHAUSTION_MARKER = "prompt is too long"
CODEX_CONTEXT_EXHAUSTION_MARKER = "context_length_exceeded"

RESERVED_LOG_RECORD_KEYS: frozenset[str] = frozenset(
    {
        "name",
        "msg",
        "args",
        "levelname",
        "levelno",
        "pathname",
        "filename",
        "module",
        "exc_info",
        "exc_text",
        "stack_info",
        "lineno",
        "funcName",
        "created",
        "msecs",
        "relativeCreated",
        "thread",
        "threadName",
        "processName",
        "process",
        "taskName",
        "message",
        "asctime",
    }
)
